sites:
  - name: splunk_blog
    url: "https://www.splunk.com/en_us/blog"
    block_css: ".card"  # 父元素的 CSS 选择器
    title_css: "a h3.splunk2-h4"  # 在父元素内部的标题选择器
    description_css: ".splunk-body.shorter-height"  # 在父元素内部的描述选择器
    link_css: "a.headline"  # 在父元素内部的链接选择器
    use_headless_browser: true
  - name: sonarsource_blog
    url: https://www.sonarsource.com/blog/tag/security/
    block_css: a.css-w2zjnb.e1yv2nyc5
    title_css: h3
    description_css: p.css-k9llvm.e1yv2nyc3
    link_css: 
    use_headless_browser: true
  - name: rapid7_blog
    url: https://www.rapid7.com/blog/tag/research/
    block_css: a.blog-all-posts__wrapper--item
    title_css: h3
    description_css: p
    link_css: 
    use_headless_browser: false
  - name: github_trending
    url: https://github.com/trending
    block_css: article.Box-row
    title_css: h2
    description_css: p
    link_css: h2 a
    use_headless_browser: false
  - name: anthropic_news
    url: https://www.anthropic.com/news
    block_css: a.PostCard_post-card___tQ6w
    title_css: h3
    description_css: .PostCard_post-info__gybiy
    link_css: 
    use_headless_browser: true
