name: Generate RSS Feed

on:
  push:
    branches:
      - main  # 或你想要的分支
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # 你可以选择合适的版本

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 feedgen pyyaml selenium webdriver-manager

      - name: Run RSS generator
        run: python rss_generator.py

      - name: Upload RSS feed
        uses: actions/upload-artifact@v3
        with:
          name: rss_feed
          path: rss_feed_*.xml  # 上传所有生成的 RSS 文件
